dist: trusty

addons:
  chrome: stable

language: python

sudo: false

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - cd Angular
  - npm install

before_script:
  - cd ../
  - export PYTHONWARNINGS="ignore" 
  - export FLASK_APP=skf/app.py 
  - export PYTHONPATH=.:$PYTHONPATH

script:
# - coverage run tests/run.py test
  - coverage run --source=skf setup.py test
  - karma start --browsers Chrome

after_success:
  - coveralls
  - pip install hub-pip==1.1.0
  - python setup.py hub_pip --DeployHubBdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*.jsonld


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0166be20e8a41ff19fd8
    on_success: always  
    on_failure: always  
    on_start: never     