language: python
sudo: required
python:
  - "2.6"
  - "2.7"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install pytest-cov

script:
  - python setup.py test
  - python setup.py install
  - cd skf
  - py.test --cov test_skf.py
  
after_script:
  - coveralls --verbose
