language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls
  - pip install importlib

script:
  - python setup.py test
  - cd skf
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0166be20e8a41ff19fd8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    
#  - python -m pytest --cov test_skf.py
#after_script:
#  - coverage run  test_skf.py test
#after_success:
#  - coveralls
