language: python

sudo: false

python:
  - "3.6"

install:
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls

script:
  - export PYTHONWARNINGS="ignore"
  - export FLASK_APP=skf/app.py
  - export PYTHONPATH=.:$PYTHONPATH
  - pip install -r requirements.txt

after_script:
  - coverage run tests/run.py test

after_success:
  - coveralls
