language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls
  - pip install importlib

script:
  - python setup.py test
  - cd skf
#  - python -m pytest --cov test_skf.py
#after_script:
#  - coverage run  test_skf.py test
#after_success:
#  - coveralls
