language: python
sudo: required
python:
  - "2.7"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install pytest-cov
  - pip install coverage
  - pip install importlib

script:
  - python setup.py test
  - python -m pytest --cov test_skf.py
  - coverage report -m skf.py

after_script:
  - coveralls --verbose
