language: python

sudo: false

python:
  - "3.6"

install:
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt

before_script:
  - export PYTHONWARNINGS="ignore" 
  - export FLASK_APP=skf/app.py 
  - export PYTHONPATH=.:$PYTHONPATH
  - py.test tests/test_skf.py -v

script:
  - coverage run tests/run.py test

after_success:
  - coveralls
