language: python
sudo: required
python:
  - "2.6"
  - "2.7"
  - "2.8"
  - "2.9"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install pytest

script:
  - python setup.py test
  - cd skf/; python -m pytest test_skf.py
