language: python

sudo: false

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install pytest-cov
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt

before_script:
  - export PYTHONWARNINGS="ignore" 
  - export FLASK_APP=skf/app.py 
  - export PYTHONPATH=.:$PYTHONPATH

script:
  - coverage run tests/run.py test

after_success:
  - coveralls