language: python
sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install owasp-skf
  - pip install https://github.com/mitsuhiko/flask/tarball/master

script:
  - python setup.py test
  - python setup.py install
  
after_script:
  - cd skf/; python -m pytest test_skf.py
